---
# Tasks to install, configure, and manage Neutron

- name: Install Neutron packages
  apt:
    name: "{{ neutron_package }}"
    state: present

- name: Configure Neutron
  template:
    src: "neutron.conf.j2"
    dest: "{{ neutron_config_file }}"

- name: Start and enable Neutron service
  service:
    name: "{{ neutron_package }}"
    state: started
    enabled: yes

