---
- name: Install Horizon package
  apt:
    name: "{{ horizon_package }}"
    state: present

- name: Configure Horizon
  template:
    src: "local_settings.py.j2"
    dest: "{{ horizon_config_file }}"

- name: Start and enable Apache service
  service:
    name: "apache2"
    state: started
    enabled: yes

